### ISSUE TITLE
Install PostgreSQL from PGDG repo 

### ISSUE THREAD

**Issue by oguya** [ilri/rmg-ansible-public#19]
Instead of relying on Ubuntu repo to provides with us a specific version of PostgreSQL, I think we should use PostgreSQL Global Development Group (PGDG) which maintains an apt repo[1][2] of PostgreSQL packages for Debian-based distros.
Using the PGDG repo, we can install a specific version of PostgreSQL on any newer/older versions of Debian-based distros. Besides that, Ubuntu 16.04 will only provide PostgreSQL 9.4 instead of our current 9.3.
1. http://apt.postgresql.org/pub/repos/apt/
2. https://wiki.postgresql.org/wiki/Apt

**Comment by alanorth** [comment]
What is the benefit of using the PGDG repository? Don't stray from distribution-vetted packages unless you need to. Occam's razor.

**Comment by oguya** [comment]
Flexibility in terms of choosing a specific version of a package. Don't forget Ubuntu 14.04 only provides one version of PostgreSQL & that is 9.3. I think this is similar to installing a specific version of nginx from nginx.org repo instead of using distro's repo. The same applies to glusterfs too.

**Comment by alanorth** [comment]
We install nginx from the PPA because we want new features, and Ubuntu's is
not just old, it's 1.4... which is two major versions behind. Do we NEED
PostgreSQL 9.4 or 9.5? Another good example, for MariaDB on boran, we
explicitly use a PPA because the distribution only provides MySQL, and we
don't like that. ;)

In the end it's not my decision, but you should remember to keep it simple
(and don't be a gentoo ricer, just tuning things to tune them). Ubuntu's
PostgreSQL maintainer is smarter than you.
