### ISSUE TITLE
systemd-timesyncd via EPEL 8

### ISSUE THREAD

**Issue by robert-scheck** [ilri/rmg-ansible-public#82]
I noticed at https://github.com/ilri/rmg-ansible-public/blob/master/roles/common/tasks/ntp.yml that you're favoring systemd-timesyncd at RHEL/CentOS 8 over a full NTP implementation. If everything goes fine [FEDORA-EPEL-2020-3fda065940](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-3fda065940) should land in EPEL 8 stable repository soon (currently: testing repository), which provides a systemd-timesyncd package. This package is of course not supported and not endorsed by Red Hat.

**Comment by alanorth** [comment]
Thanks for the heads up. Yeah we're using chrony on CentOS because Red Hat disables `systemd-timesyncd`. So you're packaging a `systemd-extras` package that will include `systemd-timesyncd`? I'll probably still stick to chrony as it's recommended by Red Hat and [did well in security audits](https://www.coreinfrastructure.org/blogs/securing-network-time/).
